# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python drops
author: Rodrigo Girão Serrão
# logo: imgs/decs.webp

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon: "imgs/favicon.png"
  baseurl: "https://drops.mathspp.com/"
  use_issues_button: true
  use_repository_button: true


sphinx:
  config:
    language: en
    html_extra_path:
      - extras
    latex_elements:
      # Set the colours for internal and external links.
      sphinxsetup: |
        InnerLinkColor={HTML}{A02F6F},
        OuterLinkColor={HTML}{A02F6F}
      extraclassoptions: "openany"
      preamble: |
        \usepackage{multicol}  % Used to set the themed index layout to 2 columns
        \setcounter{secnumdepth}{-1}  % Don't number chapters, sections, subsections, etc
        % Simplify chapter openings: title then content on same page
        \usepackage{titlesec}

        % Option A: keep the chapter number (e.g., "1") but remove the "Chapter" word
        \titleformat{\chapter}[hang]
          {\normalfont\huge\bfseries}
          {\thechapter\quad}
          {0pt}
          {}
        \titlespacing*{\chapter}{0pt}{0pt}{1.5ex}

        % If you want absolutely minimal whitespace:
        % \titlespacing*{\chapter}{0pt}{0pt}{0.75ex}
      fontpkg: |
        \usepackage{fontspec}
        \setmonofont{FiraCode NF}


exclude_patterns: [.*]
